version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: blog_redis
    ports:
      - "6379:6379"  # 로컬 포트 : 컨테이너 포트
    volumes:
      - redis_data:/data  # 데이터 영속성 유지
volumes:
  redis_data: