services:
    redis:
        image: redis:latest
        container_name: blog_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
        container_name: blog_elasticsearch
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - xpack.security.transport.ssl.enabled=false
            - xpack.security.enrollment.enabled=false
            - xpack.ml.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            interval: 10s
            timeout: 5s
            retries: 5
        command: >
            /bin/bash -c '
                elasticsearch-plugin install --batch analysis-nori &&
                /usr/local/bin/docker-entrypoint.sh elasticsearch'
        networks:
            - elastic_network

    setup-elasticsearch:
        image: curlimages/curl
        volumes:
            - ./docker/elasticsearch/mapping.json:/mapping.json  # 호스트경로:컨테이너경로(ES컨테이너 내부 경로)
        depends_on:
            elasticsearch:
                condition: service_healthy
        command: >
            sh -c '
                echo "Starting setup..." &&
                curl -X DELETE "elasticsearch:9200/posts" || true &&
                echo "Waiting for 5 seconds..." &&
                sleep 5 &&
                curl -X PUT "elasticsearch:9200/posts" -H "Content-Type: application/json" -d @/mapping.json
            '
        restart: "no"
        networks:
            - elastic_network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.16.1
        container_name: blog_kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - XPACK_SECURITY_ENABLED=false
            - XPACK_REPORTING_ENABLED=false
            - XPACK_MONITORING_ENABLED=false
            - XPACK_SECURITY_ENROLLMENT_ENABLED=false
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - elastic_network

# 볼륨 정의로 데이터 유지
volumes:
    redis_data:
    elasticsearch_data:

networks:
    elastic_network:
        driver: bridge
