services:
    redis:
        image: redis:latest
        container_name: blog_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
 
# 볼륨 정의로 데이터 유지
volumes:
    redis_data: 
 