#여러 Docker 컨테이너를 정의하고 실행하는 도구, 여러 컨테이너의 설정과 관계를 정의.  Redis 컨테이너, Prometheus 컨테이너 등등
services:
    redis:
        image: redis:latest
        container_name: blog_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    prometheus:
        image: prom/prometheus:latest
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus-dev.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.retention.time=7d"

    grafana:
        image: grafana/grafana-oss:latest
        ports:
            - "3000:3000" #localhost:3000으로 접근 가능. 기본 패스워드는 admin/admin
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        volumes:
            - grafana-storage:/var/lib/grafana

# 볼륨 정의로 데이터 유지
volumes:
    redis_data:
    grafana-storage:
