# prod 설정파일 변경 시 ec2에도 적용 필요. 
global:
    scrape_interval: 5m
    evaluation_interval: 5m
    retention_time: 3d # 일단 적게 3일 보존. 부족하면 나중에 늘리기 

 # tagets: 프로메테우스가 정기적으로(scrape_interval: 1m) 타겟 URL에 요청, 호스트 이름은 문자, 숫자, 하이픈(-)만 사용 가능
 # 동일한 네트워크를 사용하는 도커 컨테이너 내부에서는 컨테이너명(blog-app)을 사용해서 접근
scrape_configs:
    - job_name: "spring-boot-blog-app"
      metrics_path: "/actuator/prometheus"
      static_configs:
          - targets: ["blog-app:8000"]