name: Spring boot Blog CI/CD

on:
    push:
        branches: ["main"]
        paths:
            - "blog-springboot-jpa/**" # 서브디렉토리 경로 추가
    pull_request:
        branches: ["main"]
        paths:
            - "blog-springboot-jpa/**"

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./blog-springboot-jpa # 작업 디렉토리 설정

        steps:
            - uses: actions/checkout@v4

            - name: JDK 17 설정
              uses: actions/setup-java@v4
              with:
                  java-version: "17"
                  distribution: "temurin"

            - name: Gradle 캐시
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches 
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: ${{ runner.os }}-gradle-

            - name: 테스트 및 빌드
              run: |
                  chmod +x gradlew
                  ./gradlew clean build

            - name: 테스트 결과 저장
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: build/reports/tests/test/

            - name: 테스트 커버리지 생성
              run: ./gradlew jacocoTestReport

            - name: 빌드 결과물 저장
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: build/libs/*.jar
